name: Build TDLib

on:
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        container: alpine
        steps:
            - name: Install dependencies
              run: apk add --no-cache git make g++ musl-dev openssl-dev zlib-dev php gperf cmake linux-headers
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Setup ccache
              uses: 
            - name: Build
              run: |
                    mkdir td/build
                    cd td/build
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    cmake --build .
            - name: Find artifacts
              run: |
                    mkdir td/build/out
                    find td/build -name '*.a' -exec cp {} td/build/out \;
                    find td/build -name '*.so*' -exec cp {} td/build/out \;
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: tdlib
                  path: td/build/out
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: tdlib
                  path: tdlib
            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  files: tdlib/*
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: v${{ github.run_number }}
                  release_name: Release ${{ github.run_number }}
                  body: |
                      This is release ${{ github.run_number }}.
                      It contains the latest build of TDLib.
                      You can find the source code [here](
        